language: objective-c

notifications:
  email: false

before_install:
 # Make sure mono is installed,
 - wget http://download.mono-project.com/archive/3.2.4/macos-10-x86/MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg
 - sudo installer -pkg "./MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg" -target /
 - mysql -e 'create database mono;'
 - chmod 0777 nunit.sh 

env:
  - EnableNuGetPackageRestore=true

install:
 - ls
 - xbuild 
 - ./nunit.sh "Parameterized Query Tests/bin/debug/Parameterized Query Tests.dll"
