language: objective-c

notifications:
  email: false

before_install:
 # Make sure mono is installed,
 - wget http://download.mono-project.com/archive/3.2.4/macos-10-x86/MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg
 - sudo installer -pkg "./MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg" -target /
 - wget http://cdn.mysql.com/Downloads/MySQL-5.1/mysql-5.1.73-osx10.6-x86_64.dmg
 - hdiutil attach -quiet "mysql-5.1.73-osx10.6-x86_64.dmg"
 - sudo installer -pkg "/Volumes/mysql-5.1.73-osx10.6-x86_64/mysql-5.1.73-osx10.6-x86_64.pkg" -target /
 - sudo /usr/local/mysql/bin/mysqld_safe &
 #code-first will create the database
 #- mysql -u root -e 'create database mono_test'; 
 - chmod 0777 nunit.sh 

env:
  - EnableNuGetPackageRestore=true

install:
 - ls
 - xbuild 
 - ./nunit.sh "Parameterized Query Tests/bin/debug/Parameterized Query Tests.dll"
