language: objective-c

before_install:
 # Make sure mono is installed,
 - wget http://download.mono-project.com/archive/3.2.4/macos-10-x86/MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg
 - sudo installer -pkg "./MonoFramework-MDK-3.2.4.macos10.xamarin.x86.pkg" -target /

env:
  - EnableNuGetPackageRestore=true

install:
 - xbuild 
